package aplicacion;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author nebra
 */
public class Formulario extends javax.swing.JDialog {

    // se crea un objeto de PantallaPrincipal
    PantallaPrincipal pantallaPrincipal;
    // se crean variables a utilizar en esta clase
    private String nombre;
    private String apellidos;
    private String tipoEvento;
    int numeroDias;
    int numeroHabitaciones;
    private String fechaEvento;
    private String tipoCocina;

    /**
     * Creates new form Formulario
     *
     * @param parent
     * @param modal
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPrincipal = (PantallaPrincipal) parent;
        initComponents();
        setLocationRelativeTo(null);

        // Se configura el formato de visualización del JSpinnerFechaEvento para mostrar solo la fecha
        // Se almacena en primer lugar el JSpinnerFechaEvento en una nueva variable de tipo JSpinner
        JSpinner jSpinnerSoloFecha = jSpinnerFechaEvento;
        // Se crea el objeto JSpinner.DateEditor y se le da el formato que queremos.
        JSpinner.DateEditor date = new JSpinner.DateEditor(jSpinnerSoloFecha, "dd/MM/yyyy");
        // Finalmente se establece el nuevo JSpinner creado
        jSpinnerSoloFecha.setEditor(date);

        //Se establece el color de fondo personalizado para el JDialog [247, 241, 234]
        Color colorFondo = new Color(247, 241, 234);
        getContentPane().setBackground(colorFondo);

        // Se establecen inicialmente los componentes asociados a elección de "congreso" a false.
        jCheckBoxHabitaciones.setEnabled(false);
        jLabelNumeroHabitaciones.setEnabled(false);
        jSpinnerNumeroHabitaciones.setEnabled(false);
        jLabelDuracionCongreso.setEnabled(false);
        jSpinnerDiasCongreso.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerFechaEvento = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipoevento = new javax.swing.JComboBox<>();
        jSpinnerNumeroPersonas = new javax.swing.JSpinner();
        jLabelNumeroPersonas = new javax.swing.JLabel();
        jComboBoxTipoCocina = new javax.swing.JComboBox<>();
        jLabelDuracionCongreso = new javax.swing.JLabel();
        jSpinnerDiasCongreso = new javax.swing.JSpinner();
        jCheckBoxHabitaciones = new javax.swing.JCheckBox();
        jButtonConfirmarReserva = new javax.swing.JButton();
        jLabelOpcionesCocina = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTipoEvento = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTelefono = new javax.swing.JTextField();
        jLabelDPersonales = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelApellidos = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelDEvento = new javax.swing.JLabel();
        jSpinnerNumeroHabitaciones = new javax.swing.JSpinner();
        jLabelNumeroHabitaciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSpinnerFechaEvento.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jSpinnerFechaEvento.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerFechaEvento.setToolTipText("Seleccione fecha de evento");
        jSpinnerFechaEvento.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSpinnerFechaEventoPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel1.setText("Fecha de evento");

        jComboBoxTipoevento.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBoxTipoevento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banquete", "Jornada", "Congreso" }));
        jComboBoxTipoevento.setToolTipText("Seleccionar el tipo de evento");
        jComboBoxTipoevento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoeventoActionPerformed(evt);
            }
        });

        jSpinnerNumeroPersonas.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jSpinnerNumeroPersonas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jSpinnerNumeroPersonas.setToolTipText("Indique el número de personas que asistirán al evento");

        jLabelNumeroPersonas.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelNumeroPersonas.setText("Nº de personas");

        jComboBoxTipoCocina.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jComboBoxTipoCocina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bufé", "carta", "cita con chef", "no precisa" }));
        jComboBoxTipoCocina.setToolTipText("Seleccionar opciones de cocina");
        jComboBoxTipoCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoCocinaActionPerformed(evt);
            }
        });

        jLabelDuracionCongreso.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelDuracionCongreso.setText("Duración congreso (días)");
        jLabelDuracionCongreso.setToolTipText("Indicar el número de días de duración del congreso");

        jSpinnerDiasCongreso.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jSpinnerDiasCongreso.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jSpinnerDiasCongreso.setToolTipText("Indique el número de días de duración del congreso");

        jCheckBoxHabitaciones.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jCheckBoxHabitaciones.setText("habitaciones");
        jCheckBoxHabitaciones.setToolTipText("Marcar si es necesario reserva de habitaciones");
        jCheckBoxHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxHabitacionesActionPerformed(evt);
            }
        });

        jButtonConfirmarReserva.setBackground(new java.awt.Color(247, 241, 234));
        jButtonConfirmarReserva.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButtonConfirmarReserva.setText("CONFIRMAR RESERVA");
        jButtonConfirmarReserva.setToolTipText("Pulse para confirmar su reserva");
        jButtonConfirmarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarReservaActionPerformed(evt);
            }
        });

        jLabelOpcionesCocina.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelOpcionesCocina.setText("Opciones de cocina");
        jLabelOpcionesCocina.setToolTipText("Indicar opción de servicio de cocina");

        jLabelTipoEvento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelTipoEvento.setText("Tipo de evento");

        jPanel1.setBackground(new java.awt.Color(247, 241, 234));

        jLabelNombre.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelNombre.setText("Nombre");
        jLabelNombre.setToolTipText("Nombre completo de la persona que realiza la reserva");

        jTextFieldNombre.setToolTipText("Introduzca nombre completo");

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Teléfono");
        jLabel2.setToolTipText("Teléfono de contacto de la persona que realiza la reserva");

        jTextFieldTelefono.setToolTipText("Introduzca un número de teléfono de contacto");

        jLabelDPersonales.setBackground(new java.awt.Color(236, 228, 217));
        jLabelDPersonales.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelDPersonales.setText("DATOS PERSONALES");

        jLabelApellidos.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelApellidos.setText("Apellidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabelDPersonales))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNombre)
                                    .addComponent(jLabel2))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(216, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabelDPersonales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidos)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabelDEvento.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabelDEvento.setText("DATOS DEL EVENTO");
        jLabelDEvento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jSpinnerNumeroHabitaciones.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jSpinnerNumeroHabitaciones.setToolTipText("Indicar el número de habitaciones necesarias");

        jLabelNumeroHabitaciones.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelNumeroHabitaciones.setText("nº");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jComboBoxTipoevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jSpinnerFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCheckBoxHabitaciones)
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabelNumeroHabitaciones)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSpinnerNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelOpcionesCocina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jComboBoxTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDuracionCongreso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerDiasCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabelDEvento))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jButtonConfirmarReserva)))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDEvento)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTipoEvento)
                            .addComponent(jComboBoxTipoevento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumeroPersonas)
                            .addComponent(jSpinnerNumeroPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinnerFechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelOpcionesCocina)
                        .addComponent(jComboBoxTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxHabitaciones)
                    .addComponent(jLabelDuracionCongreso)
                    .addComponent(jSpinnerDiasCongreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerNumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumeroHabitaciones))
                .addGap(39, 39, 39)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButtonConfirmarReserva)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarReservaActionPerformed

        String mensaje = "¿Desea confirmar la reserva?";
        int respuesta = JOptionPane.showConfirmDialog(this, mensaje, "Confirmación", JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) { // el método JOptionPane.YES_OPTION devulve un cero.
            // Cierra el JDialog actual
            this.dispose();

            nombre = jTextFieldNombre.getText();
            apellidos = jTextFieldApellidos.getText();
            tipoEvento = jComboBoxTipoevento.getSelectedItem().toString();
            numeroDias = (int) jSpinnerDiasCongreso.getValue();
            numeroHabitaciones = (int) jSpinnerNumeroHabitaciones.getValue();
            
            // Se formatea fecha con la clase SimpleDateFormat para mostrar formato dd/mm/aa
            Date fecha = (Date) jSpinnerFechaEvento.getValue();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            fechaEvento = sdf.format(fecha);

            tipoCocina = jComboBoxTipoCocina.getSelectedItem().toString();
            
            // llamada al método de la clase principal y pasar parámetros
            pantallaPrincipal.mostrarResumenReserva(nombre, apellidos, tipoEvento, numeroDias, numeroHabitaciones, fechaEvento, tipoCocina);

            // Volvemos a la pantalla principal (JFrame pantallaPrincipal)
            pantallaPrincipal.setVisible(true);
        }


    }//GEN-LAST:event_jButtonConfirmarReservaActionPerformed

    private void jComboBoxTipoCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoCocinaActionPerformed

    private void jComboBoxTipoeventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoeventoActionPerformed

        String seleccion = (String) jComboBoxTipoevento.getSelectedItem();

        // Activa o desactiva los siguientes componentes si se elige opción "Congreso"
        if ("Congreso".equals(seleccion)) {
            // Habilita los componentes relacionados con la elección de "Congreso"
            jCheckBoxHabitaciones.setEnabled(true);
            jLabelDuracionCongreso.setEnabled(true);
            jSpinnerDiasCongreso.setEnabled(true);
        } else {
            // Deshabilita los componentes si no es un "Congreso"
            jCheckBoxHabitaciones.setEnabled(false);
            jLabelDuracionCongreso.setEnabled(false);
            jSpinnerDiasCongreso.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxTipoeventoActionPerformed

    private void jCheckBoxHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxHabitacionesActionPerformed

        // se guarda en una variable booleana el estado en el que se encuentre el componente JCheckBox
        boolean checkBoxSeleccionado = jCheckBoxHabitaciones.isSelected();

        // los dos componentes siguientes que dependen del JCheckBox cambiarán su estado en función de si está a "true" o "false"
        jLabelNumeroHabitaciones.setEnabled(checkBoxSeleccionado);
        jSpinnerNumeroHabitaciones.setEnabled(checkBoxSeleccionado);
        
        /*if (checkBoxSeleccionado){    // El comportamiento de este bloque condicional es similar al elegido arriba                        
            jLabelNumeroHabitaciones.setEnabled(true);
            jSpinnerNumeroHabitaciones.setEnabled(true);
        }*/
    }//GEN-LAST:event_jCheckBoxHabitacionesActionPerformed

    private void jSpinnerFechaEventoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSpinnerFechaEventoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerFechaEventoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConfirmarReserva;
    private javax.swing.JCheckBox jCheckBoxHabitaciones;
    private javax.swing.JComboBox<String> jComboBoxTipoCocina;
    private javax.swing.JComboBox<String> jComboBoxTipoevento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelDEvento;
    private javax.swing.JLabel jLabelDPersonales;
    private javax.swing.JLabel jLabelDuracionCongreso;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroHabitaciones;
    private javax.swing.JLabel jLabelNumeroPersonas;
    private javax.swing.JLabel jLabelOpcionesCocina;
    private javax.swing.JLabel jLabelTipoEvento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinnerDiasCongreso;
    private javax.swing.JSpinner jSpinnerFechaEvento;
    private javax.swing.JSpinner jSpinnerNumeroHabitaciones;
    private javax.swing.JSpinner jSpinnerNumeroPersonas;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
