package aplicacion;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author nebra
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    ImagenFondo fondo = new ImagenFondo();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {

        this.setContentPane(fondo);
        initComponents();
        setLocationRelativeTo(null); // centra la pantalla al iniciar la interfaz
        jPanelMensajeReservaBienvenida.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jButtonReserva = new javax.swing.JButton();
        jLabelGestionHotelera = new javax.swing.JLabel();
        jPanelMensajeReservaBienvenida = new javax.swing.JPanel();
        jLabelBienvenida = new javax.swing.JLabel();
        jLabeltipoEvento = new javax.swing.JLabel();
        jLabelnombreCompleto = new javax.swing.JLabel();
        jLabelfechaEvento = new javax.swing.JLabel();
        jLabeltipoCocina = new javax.swing.JLabel();
        jLabelnumeroDias = new javax.swing.JLabel();
        jLabelnumeroHabitaciones = new javax.swing.JLabel();
        jButtonCerrarMensaje = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenu2Reservar = new javax.swing.JMenu();
        jMenuItemreservar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemAlta = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jButtonReserva.setBackground(new java.awt.Color(236, 228, 217));
        jButtonReserva.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButtonReserva.setText("RESERVAR SALÓN HABANA");
        jButtonReserva.setToolTipText("Acceda al formulario de reserva");
        jButtonReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservaActionPerformed(evt);
            }
        });

        jLabelGestionHotelera.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabelGestionHotelera.setForeground(new java.awt.Color(247, 241, 234));
        jLabelGestionHotelera.setText("GESTIÓN HOTELERA \"LA HABANA\"");

        jPanelMensajeReservaBienvenida.setBackground(new java.awt.Color(247, 241, 234));
        jPanelMensajeReservaBienvenida.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabelBienvenida.setFont(new java.awt.Font("Georgia", 1, 16)); // NOI18N
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabeltipoEvento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabeltipoEvento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabeltipoEvento.setText("tipoEvento");

        jLabelnombreCompleto.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelnombreCompleto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelnombreCompleto.setText("nombreCompleto");

        jLabelfechaEvento.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelfechaEvento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelfechaEvento.setText("fechaEvento");

        jLabeltipoCocina.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabeltipoCocina.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabeltipoCocina.setText("tipoCocina");

        jLabelnumeroDias.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelnumeroDias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelnumeroDias.setText("numeroDias");

        jLabelnumeroHabitaciones.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabelnumeroHabitaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelnumeroHabitaciones.setText("habitaciones");

        jButtonCerrarMensaje.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButtonCerrarMensaje.setText("Cerrar");
        jButtonCerrarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMensajeReservaBienvenidaLayout = new javax.swing.GroupLayout(jPanelMensajeReservaBienvenida);
        jPanelMensajeReservaBienvenida.setLayout(jPanelMensajeReservaBienvenidaLayout);
        jPanelMensajeReservaBienvenidaLayout.setHorizontalGroup(
            jPanelMensajeReservaBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeReservaBienvenidaLayout.createSequentialGroup()
                .addGroup(jPanelMensajeReservaBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMensajeReservaBienvenidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMensajeReservaBienvenidaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelMensajeReservaBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelnumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelnumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelMensajeReservaBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelfechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeltipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeltipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelnombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelMensajeReservaBienvenidaLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jButtonCerrarMensaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMensajeReservaBienvenidaLayout.setVerticalGroup(
            jPanelMensajeReservaBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensajeReservaBienvenidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabelnombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelfechaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeltipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabeltipoCocina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelnumeroDias, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabelnumeroHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButtonCerrarMensaje)
                .addContainerGap())
        );

        jButtonSalir.setBackground(new java.awt.Color(236, 228, 217));
        jButtonSalir.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jMenuInicio.setForeground(new java.awt.Color(123, 88, 66));
        jMenuInicio.setText("Inicio");
        jMenuInicio.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuBarPrincipal.add(jMenuInicio);

        jMenu2Reservar.setForeground(new java.awt.Color(123, 88, 66));
        jMenu2Reservar.setText("Salones disponibles");
        jMenu2Reservar.setToolTipText("Pulse para ver salones disponibles");
        jMenu2Reservar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jMenuItemreservar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItemreservar.setForeground(new java.awt.Color(123, 88, 66));
        jMenuItemreservar.setText("Salón Habana");
        jMenuItemreservar.setToolTipText("Acceda al formulario de reserva del salón");
        jMenuItemreservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreservarActionPerformed(evt);
            }
        });
        jMenu2Reservar.add(jMenuItemreservar);

        jMenuItem2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(123, 88, 66));
        jMenuItem2.setText("Salón Cayo Coco");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2Reservar.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItem3.setForeground(new java.awt.Color(123, 88, 66));
        jMenuItem3.setText("Salón Varadero");
        jMenu2Reservar.add(jMenuItem3);

        jMenuBarPrincipal.add(jMenu2Reservar);

        jMenuClientes.setForeground(new java.awt.Color(123, 88, 66));
        jMenuClientes.setText("Clientes");
        jMenuClientes.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N

        jMenuItemAlta.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jMenuItemAlta.setForeground(new java.awt.Color(123, 88, 66));
        jMenuItemAlta.setText("Alta");
        jMenuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemAlta);

        jMenuBarPrincipal.add(jMenuClientes);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGestionHotelera)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jPanelMensajeReservaBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButtonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReserva)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGestionHotelera)
                .addGap(72, 72, 72)
                .addComponent(jPanelMensajeReservaBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReserva)
                    .addComponent(jButtonSalir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservaActionPerformed
        Formulario formulario = new Formulario(this, true);
        formulario.setVisible(true);
    }//GEN-LAST:event_jButtonReservaActionPerformed

    private void jMenuItemreservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreservarActionPerformed
        Formulario formulario = new Formulario(this, true);
        formulario.setVisible(true);
    }//GEN-LAST:event_jMenuItemreservarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    // Botón para cerrar jPanel con el resumen de los datos de la reserva 
    private void jButtonCerrarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarMensajeActionPerformed

        // cierra el panel completo
        jPanelMensajeReservaBienvenida.setVisible(false);
        
        /* se establecen las siguientes etiquetas como visibles por cada nueva reserva seleccionada desde la pantalla principal
        En el supuesto de no ser seleccionada la opción "Congreso", éstas pasarán a "false".
        */
        jLabelnumeroDias.setVisible(true);
        jLabelnumeroHabitaciones.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarMensajeActionPerformed

    private void jMenuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaActionPerformed

        Alta alta = new Alta(this, true);
        alta.setVisible(true);

    }//GEN-LAST:event_jMenuItemAltaActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
       
        // botón (voluntario, no exigido en la tarea) para abandonar la ventana y cerrar la aplicación
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarMensaje;
    private javax.swing.JButton jButtonReserva;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelGestionHotelera;
    private javax.swing.JLabel jLabelfechaEvento;
    private javax.swing.JLabel jLabelnombreCompleto;
    private javax.swing.JLabel jLabelnumeroDias;
    private javax.swing.JLabel jLabelnumeroHabitaciones;
    private javax.swing.JLabel jLabeltipoCocina;
    private javax.swing.JLabel jLabeltipoEvento;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2Reservar;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemAlta;
    private javax.swing.JMenuItem jMenuItemreservar;
    private javax.swing.JPanel jPanelMensajeReservaBienvenida;
    // End of variables declaration//GEN-END:variables

    class ImagenFondo extends JPanel {

        // atributos
        private Image imagen;

        // métodos
        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/imagenes/salonHotel.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);

        }

    }

    public void mostrarResumenReserva(String nombre, String apellidos, String tipoEvento, int numeroPersonas, int numeroHabitaciones, String fechaEvento, String tipoCocina) {
        
        // En los siguientes jLabels se recogen los datos procedentes del formulario de reserva.
        
        jPanelMensajeReservaBienvenida.setVisible(true);
        jLabelBienvenida.setText("¡Enhorabuena " + nombre + ", gracias por su confianza!");

        jLabelnombreCompleto.setText("Nombre completo: " + nombre + " " + apellidos);
        jLabeltipoEvento.setText("Tipo de evento: " + tipoEvento + "\n");
        
        // En el caso de la elección de "Congreso" se evalúa en esta estructura condicional 
        if (tipoEvento.equals("Congreso")) {
            jLabelnumeroDias.setText("Nº días: " + numeroPersonas);
            jLabelnumeroHabitaciones.setText("Nº habitaciones: " + numeroHabitaciones);
        } else {
            jLabelnumeroDias.setVisible(false);
            jLabelnumeroHabitaciones.setVisible(false);
        }

        jLabelfechaEvento.setText("Fecha del evento: " + fechaEvento + "\n");
        jLabeltipoCocina.setText("Opción de cocina: " + tipoCocina);

    }

}
